# Site
name: "The Design Blog by Moe Hachem"
title: "The Design Blog by Moe Hachem"
description: "Empowering designers to create a better life for all."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: https://theblog.mghachem.com
google_analytics: 'UA-143942963-1'
disqus: 'mghachem-1'
mailchimp-list: 'https://mghachem.us10.list-manage.com/subscribe/post?u=e1850c8069decdcae533cb5cb&amp;id=3ebd1eb193'
include: ["_pages"]
permalink: /:title/
email: mgh@mghachem.com

# Authors
authors:
  moe:
    name: Moe Hachem
    display_name: Moe Hachem
    avatar: 'assets/images/moe_hachem.jpg'
    email: wowthemesnet@gmail.com
    web: https://www.mghachem.com/
    linkedin: https://www.linkedin.com/in/mohamadhachem/
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
