[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "https://mghachem.com/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://mghachem.com/blog"
  status = 301
  force = true