# Redirects from what the browser requests to what we serve
https://www.blog.mghachem.com              https://www.blog.mgahchem.com/blog 301!
http://www.blog.mghachem.com              https://www.mgahchem.com/blog 301!
