[build]
  command = "echo 'No build step'"
  publish = "."
  
[[redirects]]
  from = "/*"
  to = "https://mghachem.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://mghachem.com/blog-index"
  status = 301
  force = true
