# Redirects from what the browser requests to what we serve
http://www.blog.mghachem.com/*              https://www.mgahchem.com/blog/:splat 301!
https://www.blog.mghachem.com/*             https://www.blog.mgahchem.com/blog/:splat 301!
