# Redirects from what the browser requests to what we serve
http://www.theblog.mghachem.com/*              https://www.mghachem.com/blog/:splat 301!
https://www.theblog.mghachem.com/*             https://www.blog.mghachem.com/blog/:splat 301!
